# Orchestr8r Configuration
# AI-Powered Development Orchestrator

project:
  name: "Orchestr8r Development"
  type: "mcp-server"
  
workflow:
  model: "hybrid"  # trunk-based | structured | hybrid
  
  git:
    commit_style: "conventional"  # conventional | descriptive | custom
    branch_pattern: "{type}/{ticket}-{description}"
    auto_push: true
    push_frequency: "on-complete"  # on-commit | on-complete | hourly
    
  ai:
    personality: "professional"  # professional | friendly | minimal
    verbosity: "normal"  # verbose | normal | terse
    
  patterns:
    work_hours: "9-5"
    preferred_tasks: ["features", "bugs", "docs"]
    review_reminder: "2h"
    
  integrations:
    github_projects: true
    slack_updates: false
    calendar_sync: false

# Development mode settings
development:
  debug: true
  log_level: "info"  # debug | info | warn | error
  test_mode: false 